sonar.projectKey=GoatUdder
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.javascript.lcov.reportPaths=goat-service/coverage/lcov.info,rental-service/coverage/lcov.info
sonar.sourceEncoding=UTF-8